//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AI
{
	// tututu
	private byte field
	{
		//Something wrong is going on
		get;
		set;
	}

	public virtual byte TakeATurn()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetField(byte field)
	{
		throw new System.NotImplementedException();
	}

}

