//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Field
{
    // Test test test test test test
	private byte[,] field
	{
		get;
		set;
	}

	public virtual bool CheckGameEnding()
	{
		throw new System.NotImplementedException();
	}

	public virtual byte[] ShowMe()
	{
		throw new System.NotImplementedException();
	}

	public virtual byte[] ShowEnemy()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PlaceShip(int x, int y, int lenght, bool right_rotation)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Attack(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void EraseShip(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CleanField()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GenerateShips()
	{
		throw new System.NotImplementedException();
	}

}

