//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class NetMember
{
	public virtual void SendField(byte field)
	{
		throw new System.NotImplementedException();
	}

	public virtual byte GetField()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CloseConnection()
	{
		throw new System.NotImplementedException();
	}

}

