//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Server : NetMember
{
	public virtual bool SetConnection()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool InformAndWait()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SetPriority()
	{
		throw new System.NotImplementedException();
	}

}

