//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Stat
{
	private int win_count
	{
		get;
		set;
	}

	private int number_of_battles
	{
		get;
		set;
	}

	public override string ToString()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetNumberOfBattles()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetNumberOfBattles(int num)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetWinCount(int num)
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetWinCount()
	{
		throw new System.NotImplementedException();
	}

}

